### ISSUE TITLE
REBOL System Error #1405

### ISSUE THREAD

**Issue by no-e-in** [Oldes/Rebol3#25]
On Win7-64 both Rebol_3.4.0_x64 and Rebol_3.4.0_x86 work correctly. Instead version 3.5 (x64 and x86) causes the error "REBOL System Error # 1405".

**Comment by Oldes** [comment]
Thanks... I'm now in the middle of switch to a new building system..
I will check it once I will have it done. Although I will have to find some Win7 machine first.

**Comment by Oldes** [comment]
So there is new cloud build system running now... still have to find Win7 to test if the issue is still there.
Here are various Rebol versions for Linux and Windows: https://github.com/Siskin-framework/Builder/actions/runs/625880016
(in artifact archives at the bottom of the page)

**Comment by Oldes** [comment]
Sitting on Win7 now... I can reproduce the issue even with the new builds.. I will examine it closely.
