### ISSUE TITLE
codecs/zip/verbose ignored by encode

### ISSUE THREAD

**Issue by Dobeash** [Oldes/Rebol3#52]
Setting `codecs/zip/verbose: false` works for `codecs/zip/decode` but not `codecs/zip/encode`.

**Comment by Oldes** [comment]
The question is, if there should be the `verbose` setting, because preferred way how to control verbosity is using `system/options/log`. Setting it to zero for the `zip` should silent it (except error level messages).

**Comment by Dobeash** [comment]
Yes, log setting makes more sense now.
