### ISSUE TITLE
Details on buid types for precompiled binaries

### ISSUE THREAD

**Issue by vazub** [Oldes/Rebol3#86]
Please forgive me, if I might be missing something, but is there any detailed list of differences between the **base**, **core** and **bulk** precompiled binaries to be found? Even though I had some previous exposure to Rebol/Red some time ago, I am not sure I clearly understand what "minimal additions", "a little bit more" or "almost everything" mean on the main page.

**Comment by acook** [comment]
The build `nest` file does a pretty good job of listing out what additional features are enabled:
 
- https://github.com/Oldes/Rebol3/blob/master/make/rebol3.nest#L919-L997

For example, `core` includes useful things like ANSI, clipboard support, and basic compression algorithms. And `bulk` includes rarer compression algorithms, audio and MIDI manipulation, and the ability to interpret XML and plist files.

It should be pretty easy to splice in your own favorite combination too.

**Comment by vazub** [comment]
That is exactly what I have been looking for, thanks!
